import { useState } from 'react'
import { BrowserRouter, Navigate, NavLink, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { AreaChart, Area, BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts'
import { Activity, AlertTriangle, ArrowLeft, ArrowUpRight, BarChart3, Bell, BrainCircuit, Check, ChevronRight, ClipboardCheck, Clock3, FileSearch, Fingerprint, FolderKanban, GitBranch, LayoutDashboard, Network, Play, Plus, Search, ShieldCheck, Sparkles, UserRound, X } from 'lucide-react'
import { cases } from './data'
import { getAnalytics, runInvestigation } from './services/investigationEngine'
import './App.css'

const riskClass = (value) => value.toLowerCase().replaceAll(' ', '-')

export default function App() {
  const [statusOverrides, setStatusOverrides] = useState({})
  const [notes, setNotes] = useState({})
  const updateStatus = (caseId, status) => setStatusOverrides((current) => ({ ...current, [caseId]: status }))
  const saveNote = (caseId, note) => setNotes((current) => ({ ...current, [caseId]: note }))

  return <BrowserRouter><Routes>
    <Route path="/" element={<Landing />} />
    <Route path="/dashboard" element={<Workspace><Dashboard /></Workspace>} />
    <Route path="/analytics" element={<Workspace><DynamicAnalyticsPage /></Workspace>} />
    <Route path="/case-files" element={<Workspace><CaseFiles /></Workspace>} />
    <Route path="/evidence-graph" element={<Workspace><DynamicEvidenceGraphPage /></Workspace>} />
    <Route path="/review-queue" element={<Workspace><DynamicReviewQueue /></Workspace>} />
    <Route path="/cases/:caseId" element={<Workspace><CasePage statusOverrides={statusOverrides} updateStatus={updateStatus} notes={notes} saveNote={saveNote} /></Workspace>} />
    <Route path="*" element={<Navigate to="/dashboard" replace />} />
  </Routes></BrowserRouter>
}

function Workspace({ children }) {
  const [quickPanel, setQuickPanel] = useState(null)
  return <div className="app-shell"><Sidebar onAccount={() => setQuickPanel('account')} /><main className="main-content"><Topbar onNotifications={() => setQuickPanel('notifications')} />{children}</main>{quickPanel && <QuickPanel type={quickPanel} onClose={() => setQuickPanel(null)} />}</div>
}

function Topbar({ onNotifications }) {
  const location = useLocation()
  const labels = { '/analytics': 'Analytics', '/case-files': 'Case files', '/evidence-graph': 'Evidence graph', '/review-queue': 'Review queue', '/dashboard': 'Overview' }
  const label = location.pathname.startsWith('/cases/') ? 'Case investigation' : labels[location.pathname] || 'Overview'
  return <header className="topbar"><div className="mobile-brand"><Fingerprint size={19} /> TRACE//AI</div><div className="crumb">Workspace / <strong>{label}</strong></div><div className="top-actions"><button className="icon-button" aria-label="Notifications" onClick={onNotifications}><Bell size={17} /><i /></button><div className="user"><span>AN</span><div><strong>Analyst</strong><small>Investigation Unit</small></div></div></div></header>
}

function Sidebar({ onAccount }) {
  const location = useLocation()
  const overviewActive = location.pathname === '/dashboard' || location.pathname.startsWith('/cases/')
  const links = [
    { to: '/dashboard', label: 'Case overview', icon: LayoutDashboard, active: overviewActive, count: '08' },
    { to: '/analytics', label: 'Analytics', icon: BarChart3 },
    { to: '/case-files', label: 'Case files', icon: FolderKanban },
    { to: '/evidence-graph', label: 'Evidence graph', icon: Network },
    { to: '/review-queue', label: 'Review queue', icon: ClipboardCheck, count: '3' },
  ]
  const renderLink = ({ to, label, icon: Icon, active, count }) => <NavLink key={to} to={to} className={({ isActive }) => active || isActive ? 'nav-item active' : 'nav-item'}><Icon size={17} /> {label}{count && <span className={to === '/review-queue' ? 'nav-pip' : 'nav-count'}>{count}</span>}</NavLink>
  return <aside className="sidebar"><NavLink to="/dashboard" className="brand"><span className="brand-mark"><Fingerprint size={20} /></span><span>TRACE<span>//AI</span></span></NavLink><div className="sidebar-label">Investigation desk</div><nav>{links.slice(0, 2).map(renderLink)}</nav><div className="sidebar-label lower">Workspace</div><nav>{links.slice(2).map(renderLink)}</nav><div className="sidebar-bottom"><div className="system-state"><span className="live-dot" /><div><strong>All systems nominal</strong><small>Last sync 2 min ago</small></div></div><button className="nav-item" onClick={onAccount}><UserRound size={17} /> Account</button></div></aside>
}

function QuickPanel({ type, onClose }) { const notifications = type === 'notifications'; return <div className="quick-panel-backdrop" onClick={onClose}><section className="quick-panel" onClick={(event) => event.stopPropagation()}><div className="panel-heading"><div><span className="panel-kicker">{notifications ? 'WORKSPACE ALERTS' : 'ANALYST PROFILE'}</span><h2>{notifications ? 'Notifications' : 'Account'}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close panel"><X size={16} /></button></div>{notifications ? <div className="quick-item"><span className="live-dot" /><div><strong>Review queue updated</strong><small>4 cases currently require investigation attention.</small></div></div> : <div className="quick-item"><span className="profile-mark">AN</span><div><strong>Analyst</strong><small>Investigation Unit · Demo workspace</small></div></div>}<button className="ghost-button quick-close" onClick={onClose}>Close</button></section></div> }

function Landing() { const navigate = useNavigate(); return <div className="landing"><div className="landing-grid" /><div className="landing-nav"><NavLink to="/dashboard" className="brand"><span className="brand-mark"><Fingerprint size={20} /></span><span>TRACE<span>//AI</span></span></NavLink><div className="landing-status"><span className="live-dot" /> LOCAL DEMO ENVIRONMENT</div></div><div className="landing-content"><div className="eyebrow"><span /> NATIONAL INVESTIGATION INTELLIGENCE PLATFORM</div><h1>See the signal<br /><em>behind the spend.</em></h1><p>AI-assisted anomaly intelligence for procurement and project-spending investigations. Trace patterns, connect evidence, and keep human judgment at the center.</p><button className="primary-button enter-button" onClick={() => navigate('/dashboard')}>Enter workspace <ArrowUpRight size={18} /></button><div className="landing-note"><ShieldCheck size={15} /> Synthetic data · No external APIs required</div></div><div className="landing-visual"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="radar"><div className="radar-line" /><div className="radar-core"><Fingerprint size={30} /></div><span className="radar-label label-a">ANOMALY 91</span><span className="radar-label label-b">EVIDENCE LINKED</span><span className="radar-label label-c">CASE-1042</span></div></div><div className="landing-footer"><span>v0.9.1 · DEMO BUILD</span><span>PROCUREMENT INTELLIGENCE / 2026</span></div></div> }

function Dashboard() { const navigate = useNavigate(); const summary = getAnalytics(); const stats = [{ label: 'Total cases', value: String(summary.total).padStart(2, '0'), delta: 'Synthetic records tracked', icon: FolderKanban }, { label: 'Critical cases', value: String(summary.critical).padStart(2, '0'), delta: 'Requires attention', icon: AlertTriangle, accent: true }, { label: 'Under investigation', value: String(summary.underInvestigation).padStart(2, '0'), delta: 'Priority review queue', icon: Clock3 }, { label: 'Anomalies detected', value: String(summary.totalAnomalies).padStart(2, '0'), delta: `Average score ${summary.averageScore}`, icon: Activity }]; return <div className="page"><PageHeading eyebrow="INVESTIGATION DESK" title="Case overview" copy="Monitor suspicious spending patterns across active investigations." action={<button className="ghost-button" onClick={() => navigate('/case-files')}><Plus size={16} /> New watchlist</button>} /><div className="stats-grid">{stats.map(({ label, value, delta, icon: Icon, accent }) => <div className="stat-card" key={label}><div className={'stat-icon ' + (accent ? 'accent' : '')}><Icon size={18} /></div><div className="stat-label">{label}</div><div className="stat-value">{value}</div><div className="stat-delta">{delta}</div></div>)}</div><div className="section-head"><div><h2>Recent investigation cases</h2><span className="muted">Prioritized by anomaly score and recency</span></div><NavLink className="text-button" to="/analytics">View analytics <ChevronRight size={15} /></NavLink></div><CaseTable onOpen={(item) => navigate(`/cases/${item.id}`)} /><Disclaimer /></div> }
function PageHeading({ eyebrow, title, copy, action }) { return <div className="page-heading"><div><div className="eyebrow"><span /> {eyebrow}</div><h1>{title}</h1><p>{copy}</p></div>{action}</div> }
function CaseTable({ onOpen, records = cases }) { return <div className="case-table"><div className="table-head"><span>Case ID</span><span>Project / vendor</span><span>Amount</span><span>Risk score</span><span>Status</span><span>Date</span><span /></div>{records.map((item) => { const result = runInvestigation(item.caseId); return <button className="table-row" key={item.caseId} onClick={() => onOpen(item)}><span className="case-id">{item.caseId}{item.caseId === 'CASE-1042' && <span className="demo-tag">DEMO</span>}</span><span className="project-cell"><strong>{item.projectName}</strong><small>{item.vendor}</small></span><span className="amount">₹{item.invoiceAmount.toLocaleString('en-IN')}</span><span><span className={'risk-score ' + result.riskLevel.toLowerCase()}><i />{result.riskScore}</span></span><span><span className={'status ' + riskClass(item.status)}>{item.status}</span></span><span className="date">{item.invoiceDate}</span><span><ChevronRight size={16} className="row-arrow" /></span></button> })}</div> }
function Disclaimer() { return <div className="disclaimer"><ShieldCheck size={15} /><span>TRACE//AI identifies suspicious patterns for human investigation. It does not determine fraud, guilt, or intent.</span></div> }

function CaseFiles() { const navigate = useNavigate(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All'); const filters = ['All', 'Critical', 'High', 'Medium', 'Low', 'Under Investigation', 'Reviewed']; const filtered = cases.filter((item) => { const matchesQuery = `${item.caseId} ${item.projectName} ${item.department} ${item.vendor}`.toLowerCase().includes(query.toLowerCase()); const matchesFilter = filter === 'All' || (filter === 'Under Investigation' || filter === 'Reviewed' ? item.status === filter : runInvestigation(item.caseId).riskLevel === filter.toUpperCase()); return matchesQuery && matchesFilter }); return <div className="page"><PageHeading eyebrow="WORKSPACE / CASE FILES" title="Case Files" copy="Search and inspect every synthetic investigation record." action={<span className="muted">{filtered.length} of {cases.length} cases</span>} /><div className="files-toolbar"><div className="search-field"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search cases..." /></div><div className="filter-row">{filters.map((item) => <button key={item} className={filter === item ? 'filter-button active' : 'filter-button'} onClick={() => setFilter(item)}>{item}</button>)}</div></div><CaseTable records={filtered} onOpen={(item) => navigate(`/cases/${item.caseId}`)} /><Disclaimer /></div> }

function DynamicEvidenceGraphPage() { const [selectedId, setSelectedId] = useState('CASE-1042'); const [selectedNode, setSelectedNode] = useState(null); const selected = cases.find((item) => item.caseId === selectedId) || cases[0]; const data = runInvestigation(selected.caseId); return <div className="page"><PageHeading eyebrow="WORKSPACE / RELATIONSHIPS" title="Evidence Graph" copy="Trace connected procurement, payment, and project records." action={<label className="case-select">Select case<select value={selectedId} onChange={(event) => { setSelectedId(event.target.value); setSelectedNode(null) }}>{cases.map((item) => <option key={item.caseId} value={item.caseId}>{item.caseId} · {item.projectName}</option>)}</select></label>} /><section className="panel graph-page-panel"><div className="panel-heading"><div><span className="panel-kicker"><GitBranch size={13} /> CASE RELATIONSHIP MAP</span><h2>{selected.caseId} / {selected.vendor}</h2></div><span className={'risk-score ' + data.riskLevel.toLowerCase()}><i />Risk {data.riskScore}</span></div><div className="graph-stack">{data.evidence.map((item, index) => <div key={`${item.type}-${item.label}`} className="graph-stack-item"><button className={'evidence-node ' + item.tone} onClick={() => setSelectedNode(item)}><span>{item.type}</span><strong>{item.label}</strong><small>{item.meta}</small></button>{index < data.evidence.length - 1 && <div className="graph-arrow"><ChevronRight size={17} /></div>}</div>)}</div>{selectedNode && <div className="saved-note"><FileSearch size={15} /><span><strong>{selectedNode.type}:</strong> {selectedNode.label} · {selectedNode.meta}</span></div>}<div className="related-list"><div className="related-head"><span>Related invoices, payments and project records</span><span>{data.related.length} linked</span></div>{data.related.map((item) => <div className="related-row" key={item.id}><span className="record-icon"><FileSearch size={14} /></span><div><strong>{item.id}</strong><small>{item.label}</small></div><strong>{typeof item.amount === 'number' ? `₹${item.amount.toLocaleString('en-IN')}` : item.amount}</strong><small>{item.date}</small></div>)}</div></section><Disclaimer /></div> }

function EvidenceGraphPage() { return <DynamicEvidenceGraphPage /> }

function DynamicReviewQueue() { const navigate = useNavigate(); const [filter, setFilter] = useState('All'); const [department, setDepartment] = useState('All'); const [vendor, setVendor] = useState('All'); const priorities = cases.map((item) => ({ item, result: runInvestigation(item.caseId) })).sort((left, right) => right.result.riskScore - left.result.riskScore); const departments = ['All', ...new Set(cases.map((item) => item.department))]; const vendors = ['All', ...new Set(cases.map((item) => item.vendor))]; const queued = priorities.filter(({ item, result }) => (filter === 'All' || result.riskLevel === filter) && (department === 'All' || item.department === department) && (vendor === 'All' || item.vendor === vendor)); return <div className="page"><PageHeading eyebrow="HUMAN REVIEW WORKSPACE" title="Review Queue" copy="Cases requiring investigator attention and verification." action={<span className="nav-pip queue-count">{queued.length} pending</span>} /><div className="files-toolbar"><div className="filter-row">{['All', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].map((item) => <button key={item} className={filter === item ? 'filter-button active' : 'filter-button'} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="filter-row"><select className="case-select" value={department} onChange={(event) => setDepartment(event.target.value)}><option value="All">All departments</option>{departments.slice(1).map((item) => <option key={item}>{item}</option>)}</select><select className="case-select" value={vendor} onChange={(event) => setVendor(event.target.value)}><option value="All">All vendors</option>{vendors.slice(1).map((item) => <option key={item}>{item}</option>)}</select></div></div><div className="review-table"><div className="review-head"><span>Case ID</span><span>Risk score</span><span>Priority</span><span>Reason</span><span>Assigned to</span><span>Status</span><span>Action</span></div>{queued.map(({ item, result }) => <div className="review-row" key={item.caseId}><strong className="case-id">{item.caseId}</strong><span className={'risk-score ' + result.riskLevel.toLowerCase()}><i />{result.riskScore}</span><span className="priority">{result.riskLevel}</span><span className="review-reason">{result.findings[0]}</span><span className="assigned">Investigator</span><span className={'status ' + riskClass(item.status)}>{item.status}</span><div className="review-actions"><button className="text-button" onClick={() => navigate(`/cases/${item.caseId}`)}>Review Case</button><button className="ghost-button" onClick={() => navigate(`/cases/${item.caseId}`)}>Open Investigation</button></div></div>)}</div><Disclaimer /></div> }

function ReviewQueue() { return <DynamicReviewQueue /> }

function CasePage({ statusOverrides, updateStatus, notes, saveNote }) {
  const { caseId } = useParams(); const navigate = useNavigate(); const sourceCase = cases.find((item) => item.caseId === caseId); const selectedCase = sourceCase ? { ...sourceCase, ...runInvestigation(caseId) } : null
  const [investigation, setInvestigation] = useState(null); const [running, setRunning] = useState(false); const [stage, setStage] = useState(0); const [noteOpen, setNoteOpen] = useState(false); const [draft, setDraft] = useState(''); const [requestError, setRequestError] = useState('')
  if (!selectedCase) return <Navigate to="/dashboard" replace />
  const status = statusOverrides[caseId] || selectedCase.status
  const startInvestigation = async () => { setRunning(true); setRequestError(''); setStage(1); const timers = [550, 1050, 1550, 2050].map((delay, index) => window.setTimeout(() => setStage(index + 2), delay)); try { const result = await runInvestigation(caseId); setInvestigation(result); setStage(6) } catch { timers.forEach((timer) => window.clearTimeout(timer)); setRequestError('Investigation could not be completed. Please retry.'); setStage(-1) } finally { setRunning(false) } }
  const stages = ['Anomaly detection', 'Vendor history analysis', 'Related transaction analysis', 'Timeline reconstruction', 'Evidence correlation', 'AI investigation reasoning']
  return <div className="page case-page"><div className="breadcrumbs"><button onClick={() => navigate('/dashboard')}>Investigation Desk</button><ChevronRight size={13} /><button onClick={() => navigate('/dashboard')}>Case Overview</button><ChevronRight size={13} /><strong>{caseId}</strong></div><button className="back-button" onClick={() => navigate('/dashboard')}><ArrowLeft size={15} /> Back to case overview</button><div className="case-heading"><div><div className="eyebrow"><span /> CASE FILE / {caseId}</div><h1>{selectedCase.project}</h1><p>{selectedCase.vendor} <span className="dot-sep">•</span> {selectedCase.invoice}</p></div><div className="case-heading-actions"><span className={'status ' + riskClass(status)}>{status}</span>{!investigation && !running && <button className="primary-button run-button" onClick={startInvestigation}><Sparkles size={17} /> Run AI investigation</button>}{investigation && <button className="ghost-button"><FileSearch size={16} /> Export report</button>}</div></div><div className="case-summary"><div><span>Case ID</span><strong>{caseId}</strong></div><div><span>Invoice amount</span><strong>₹{selectedCase.amount.toLocaleString('en-IN')}</strong></div><div><span>Risk level</span><strong className="high-text">{selectedCase.riskLevel}</strong></div><div><span>Current status</span><strong>{status}</strong></div><div className="score-block"><span>Risk score</span><strong>{selectedCase.riskScore} <small>/ 100</small></strong><div className="score-bar"><i style={{ width: `${selectedCase.riskScore}%` }} /></div></div></div>{(running || !investigation) && <AnalysisPanel running={running} stage={stage} stages={stages} requestError={requestError} onRun={startInvestigation} />}{investigation && <InvestigationResult data={investigation} status={status} updateStatus={() => updateStatus(caseId, 'Reviewed')} onEscalate={() => updateStatus(caseId, 'Escalated')} note={notes[caseId]} onAddNote={() => setNoteOpen(true)} />}{noteOpen && <NoteModal value={draft} setValue={setDraft} onClose={() => setNoteOpen(false)} onSave={() => { if (draft.trim()) saveNote(caseId, draft.trim()); setDraft(''); setNoteOpen(false) }} />}</div>
}

function AnalysisPanel({ running, stage, stages, requestError, onRun }) { const failed = stage < 0; return <div className={'analysis-panel ' + (running ? 'is-running' : '')}><div className="analysis-copy"><div className="analysis-orb"><BrainCircuit size={23} /></div><div><h2>{running ? 'Analyzing connected evidence...' : failed ? 'Investigation error' : 'Ready to investigate'}</h2><p>{running ? 'Analyzing connected evidence...' : failed ? requestError : 'Run the local investigation engine to surface connected anomalies and evidence.'}</p></div></div>{running ? <div className="stage-list">{stages.map((item, index) => <div className={'stage ' + (index + 1 < stage ? 'done' : index + 1 === stage ? 'current' : '')} key={item}><span>{index + 1 < stage ? <Check size={13} /> : index + 1}</span>{item}{index + 1 === stage && <i />}</div>)}</div> : <button className="primary-button run-button" onClick={onRun}><Play size={15} fill="currentColor" /> {failed ? 'Retry analysis' : 'Start analysis'}</button>}</div> }
function InvestigationResult({ data, status, updateStatus, onEscalate, note, onAddNote }) { return <><div className="section-head result-head"><div><h2>Investigation findings</h2><span className="muted">Model-assisted review of linked procurement records</span></div><span className="generated"><span className="live-dot" /> Investigation completed</span></div><div className="anomaly-grid">{data.anomalies.map((item) => <AnomalyCard key={item.title} item={item} />)}</div><div className="investigation-grid"><EvidenceGraph data={data} /><Timeline data={data.timeline} /></div><Report data={data} status={status} updateStatus={updateStatus} onEscalate={onEscalate} note={note} onAddNote={onAddNote} /></> }
function AnomalyCard({ item }) { return <div className="anomaly-card"><div className="anomaly-top"><span className="anomaly-icon"><AlertTriangle size={15} /></span><span className="severity">SIGNAL {item.score}</span></div><h3>{item.title}</h3><div className="anomaly-metrics"><div><span>Detected value</span><strong>{item.value}</strong></div><div><span>Expected range</span><strong>{item.expected}</strong></div></div><div className="anomaly-score"><div><span>Anomaly score</span><strong>{item.score}/100</strong></div><div className="mini-bar"><i style={{ width: `${item.score}%` }} /></div></div><p>{item.explanation}</p></div> }
function EvidenceGraph({ data }) { return <section className="panel evidence-panel"><div className="panel-heading"><div><span className="panel-kicker"><GitBranch size={13} /> RELATIONSHIP MAP</span><h2>Connected evidence</h2></div></div><div className="evidence-flow">{data.evidence.map((item, index) => <div className="evidence-node-wrap" key={item.type}><div className={'evidence-node ' + item.tone}><span>{item.type}</span><strong>{item.label}</strong><small>{item.meta}</small></div>{index < data.evidence.length - 1 && <div className="flow-line"><ChevronRight size={14} /></div>}</div>)}</div><div className="related-list"><div className="related-head"><span>Related records</span><span>{data.related.length} linked</span></div>{data.related.map((item) => <div className="related-row" key={item.id}><span className="record-icon"><FileSearch size={14} /></span><div><strong>{item.id}</strong><small>{item.label}</small></div><strong>{item.amount}</strong><small>{item.date}</small></div>)}</div></section> }
function Timeline({ data }) { return <section className="panel timeline-panel"><div className="panel-heading"><div><span className="panel-kicker"><Clock3 size={13} /> EVENT SEQUENCE</span><h2>Timeline reconstruction</h2></div></div><div className="timeline">{data.map((item, index) => <div className={'timeline-item ' + (item.flag ? 'flagged' : '')} key={item.event}><div className="timeline-marker">{item.flag ? <AlertTriangle size={12} /> : <span>{String(index + 1).padStart(2, '0')}</span>}</div><div><span className="timeline-date">{item.date}</span><strong>{item.event}</strong><small>{item.detail}</small></div></div>)}</div></section> }
function Report({ data, status, updateStatus, onEscalate, note, onAddNote }) { const [checks, setChecks] = useState([]); const toggle = (index) => setChecks((current) => current.includes(index) ? current.filter((item) => item !== index) : [...current, index]); return <section className="report-section"><div className="report-card"><div className="report-header"><div><span className="panel-kicker"><BrainCircuit size={13} /> AI INVESTIGATION SUMMARY</span><h2>Pattern assessment</h2></div><div className="report-score"><span>RISK SCORE</span><strong>{data.riskScore}<small>/100</small></strong><span className="high-text">HIGH PRIORITY</span></div></div><div className="report-columns"><div><h3>Key findings</h3><ol>{data.findings.map((finding) => <li key={finding}>{finding}</li>)}</ol><div className="caution"><AlertTriangle size={16} /><span><strong>Suspicious pattern detected.</strong> Further human verification is recommended before any determination.</span></div></div><div className="explanations"><h3>Possible explanations</h3>{data.explanations.map((item) => <span key={item}>{item}</span>)}</div></div></div><div className="actions-card"><div className="panel-heading"><div><span className="panel-kicker"><ClipboardCheck size={13} /> NEXT STEPS</span><h2>Recommended investigation actions</h2></div><span className="progress-count">{checks.length}/{data.recommendations.length}</span></div><div className="checklist">{data.recommendations.map((item, index) => <button key={item} className={checks.includes(index) ? 'checked' : ''} onClick={() => toggle(index)}><span>{checks.includes(index) && <Check size={13} />}</span>{item}</button>)}</div></div>{note && <div className="saved-note"><ClipboardCheck size={15} /><span><strong>Investigation note:</strong> {note}</span></div>}<div className="decision-bar"><div><span>AI recommendation</span><strong>Prioritize for human review</strong></div><div className="decision-actions"><button className="ghost-button" onClick={onAddNote}><Plus size={15} /> Add note</button><button className="outline-danger" onClick={onEscalate}><AlertTriangle size={15} /> Escalate</button><button className={'primary-button ' + (status === 'Reviewed' ? 'reviewed-button' : '')} onClick={updateStatus}>{status === 'Reviewed' ? <Check size={16} /> : <ClipboardCheck size={16} />} {status === 'Reviewed' ? 'Marked as reviewed' : 'Mark as reviewed'}</button></div></div></section> }
function NoteModal({ value, setValue, onClose, onSave }) { return <div className="modal-backdrop"><div className="note-modal"><div className="panel-heading"><div><span className="panel-kicker">INVESTIGATION LOG</span><h2>Add investigation note</h2></div><button className="icon-button" onClick={onClose} aria-label="Close note dialog"><X size={16} /></button></div><textarea value={value} onChange={(event) => setValue(event.target.value)} placeholder="Record a verification step, observation, or follow-up..." autoFocus /><div className="modal-actions"><button className="ghost-button" onClick={onClose}>Cancel</button><button className="primary-button" onClick={onSave}>Save note</button></div></div></div> }

function DynamicAnalyticsPage() { const analytics = getAnalytics(); const colors = ['#e77855', '#e9a84e', '#56a987', '#5b8fd1']; return <div className="page analytics-page"><PageHeading eyebrow="SIGNAL INTELLIGENCE" title="Analytics" copy="Portfolio-level signals across the investigation workspace." action={<span className="muted">Demo Dataset · Synthetic Data</span>} /><div className="stats-grid"><div className="stat-card"><div className="stat-label">Total cases</div><div className="stat-value">{analytics.total}</div><div className="stat-delta">Calculated from dataset</div></div><div className="stat-card"><div className="stat-label">Average anomaly score</div><div className="stat-value">{analytics.averageScore}</div><div className="stat-delta">Deterministic engine score</div></div><div className="stat-card"><div className="stat-label">Critical cases</div><div className="stat-value">{analytics.critical}</div><div className="stat-delta">Priority review</div></div><div className="stat-card"><div className="stat-label">Under investigation</div><div className="stat-value">{analytics.underInvestigation}</div><div className="stat-delta">Current status</div></div></div><div className="analytics-top"><div className="metric-panel"><span>Average investigation score</span><strong>{analytics.averageScore}</strong><small><ArrowUpRight size={13} /> Calculated from all cases</small><div className="sparkline"><ResponsiveContainer width="100%" height="65"><AreaChart data={analytics.trend}><Area type="monotone" dataKey="cases" stroke="#e77855" fill="#e77855" fillOpacity=".12" strokeWidth={2} /></AreaChart></ResponsiveContainer></div></div><div className="chart-panel"><div className="panel-heading"><div><span className="panel-kicker">DISTRIBUTION</span><h2>Cases by risk level</h2></div></div><div className="donut-chart"><ResponsiveContainer width="130" height="130"><PieChart><Pie data={analytics.riskLevels} dataKey="value" innerRadius={42} outerRadius={59} strokeWidth={0}>{analytics.riskLevels.map((_, index) => <Cell key={index} fill={colors[index]} />)}</Pie></PieChart></ResponsiveContainer><div><strong>{analytics.total}</strong><small>cases</small></div></div><div className="legend">{analytics.riskLevels.map((item, index) => <span key={item.name}><i style={{ background: colors[index] }} />{item.name}<strong>{item.value}</strong></span>)}</div></div><div className="chart-panel"><div className="panel-heading"><div><span className="panel-kicker">SIGNAL BREAKDOWN</span><h2>Anomaly categories</h2></div></div><ResponsiveContainer width="100%" height="150"><BarChart data={analytics.anomalies}><XAxis dataKey="name" hide /><YAxis hide /><Tooltip /><Bar dataKey="value" fill="#d4a65a" radius={[3, 3, 0, 0]} barSize={18} /></BarChart></ResponsiveContainer></div></div><Disclaimer /></div> }

function AnalyticsPage() { return <DynamicAnalyticsPage /> }
